# Generated by Django 4.0.10 on 2023-03-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
